### ISSUE TITLE
Want to play

### ISSUE THREAD

**Issue by Zyzzyva0381** [Flywheel-Gregcraft-Developer-Group/Flywheel-Gregcraft#8]
浇浇我机械动力

**Comment by Golandro** [comment]
You can see the "ponder"（思索） in the game, which is the best guide for beginners.
Or you can have a detailed encyclopaedia at https://www.mcmod.cn/class/2021.html

**Comment by Zyzzyva0381** [comment]
Thank you for the counsel.

**Comment by Golandro** [comment]
If you need help about game play, please don't mean to ask for help fron other players, rather than tick an issue there.
(sorry for my English skills having been dropping down seriously)

**Comment by Zyzzyva0381** [comment]
Thank you for offering help to us all.
